# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ba39d8f1644b1b9889c3ff8d710fcf0b8279ae2bd90a9441247da285dc1595416d15ffe6f61d7c53531ea5198e0748778acf39c45434d2ce24df9f32f113a02

test:
  secret_key_base: bdf4ea762d39b1d50f383b91a59f4e168ff758a2c4c07e06374d81363f7fd87d80e344cdb5f2cf2b193fe9b6770bc3ecfbe2515be2155f44784290edd4aad0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
